---
title: "Reaction to government’s energy price cap announcement"
author: "Christian Spence"
date: "2022-09-08"
categories: [energy prices]
---

The government’s announcement of a unit price cap on energy for the next two years (which will result in the average household’s bills being around £2,500 per year) will provide some welcome certainty in terms of budget planning. This is still a substantial increase above where prices were before the invasion of Ukraine, and a large share of households will still require additional support above what has already been pledged to ensure that their energy bills remain affordable.

The decision to extend this cap to businesses will be a relief for many, however limiting this to just six months leaves significant uncertainty over planning for the coming year and may cause some challenges for businesses seeking to renegotiate annual contracts at this traditional time of year. We now have to wait for a review that will decide which sectors will fall under a definition of “vulnerable industries” that may receive additional support after the six month period. Government must aim to conclude this review as quickly as is practicable, and include business organisations closely in that process.

Government has not estimated the cost of this intervention but it is likely to exceed £100bn with little to no clue as to how that will be financed. With significant tax cuts pledged to be announced at an emergency budget expected later this month, this is likely to place additional challenges on the public debt and also on interest rates. Whilst Sterling has responded positively to the news (and its strengthening will take some pressure off imported inflation), this is also because this additional boost to household incomes may well feed through into higher domestic inflation and cause the Bank of England to increase base rates faster than was previously expected.

It is welcome that the new government has moved quickly to reassure consumers and businesses on energy prices, but there is much missing from this statement that will need to be concluded swiftly over the coming weeks. Even with this price cap in place, consumer spending will remain under pressure and businesses will need further reassurance if they are to plan through into 2023 with confidence.