---
title: "Research & Publications"
---

Spence, C. (2018 (forthcoming)). City-led industrial strategy. (Book chapter)

Spence, C. (2018). The future of bus travel in cities. Prospect Magazine.

Spence, C. (2018). Sub-sectoral analysis of manufacturing in the North West pre- and post-recession. Greater Manchester Chamber of Commerce.

Spence, C. (2017). The digital future: what should business know? Prospect Magazine.

Spence, C., Krishnan Harihara, S., Davies, A. (2017). Northern Powerhouse Construction Pipeline Analysis. Greater Manchester Chamber of Commerce.

Spence, C. (2017). The Seven Deadly Sins of Business Rates. British Chambers of Commerce

Spence, C. (2017). Local Government Finance Bill Committee Evidence: incoherence in the approach. British Chambers of Commerce.

Spence, C. (2017). Business rates retention and its impact on local authorities’ relationship with business. British Chambers of Commerce.

Spence, C. (2016). Business rates appeals regulation: devil in the detail. British Chambers of Commerce.

Spence, C. (2016). Business rates: reforming the appeals system. British Chambers of Commerce.

Spence, C. (2015). DCLG Select Committee Evidence: business rates reform. British Chambers of Commerce.

Spence, C. (2015). Business rates: delivering more frequent revaluations. British Chambers of Commerce.

Spence, C. (2015). Heathrow Expansion Skills Legacy Analysis. Heathrow Airport.

Spence, C., Krishnan Harihara, S. (2015). North West Construction Pipeline Analysis. Greater Manchester Chamber of Commerce.

Spence, C. (2014). Business rates administration review: areas for improvement. British Chambers of Commerce.

Spence, C. (2014). Business rates: time for reform. British Chambers of Commerce.

Spence, C. (2013). Greater Manchester Construction Pipeline Skills Analysis. Greater Manchester Chamber of Commerce.

Spence, C. (2012). Late payments: the impact on SMEs and policy reform. Greater Manchester Chamber of Commerce.

Spence, C. (2011). Devolution to cities and legislative reform. (Includes drafting of accepted legislative amendments for Localism Bill). Core Cities