---
title: "Thoughts from an English vacation"
author: "Christian Spence"
date: "2018-09-02"
categories: [economics, urban-rural, towns]
---

My partner and I are keen city-break fans. We try and get to different places across Europe regularly, and enjoy the experience of the different histories and cultures that they provide. But, we’ve not done all that much travelling around the UK, and outside our working city of Manchester, don’t really know much of our own country well outside other northern cities (including Edinburgh, perhaps for me the UK’s most European city) and, of course, London. So, whilst the weather in the UK has been good this summer, we planned a week of travelling around the East and West Midlands.

Perhaps the biggest and most pleasant surprise was Coventry, a city I’ve often heard remarked on as a concrete jungle. Yes, there’s lots of it, but it had a interesting feel to it, some great pubs and excellent restaurants, and an open, friendly and vibrant feel to it, and you see clearly what the planners were attempting to create in its pedestrianised centre.

But the places that captured my imagination the most were Lincoln and Newark. One an ancient city, seemingly surprisingly off the tourist trail (despite one of the very finest cathedrals in the UK and a fine castle and old town) and one an old market town, they struck me as being quite similar.

Though I’ve moved around the north over the years, I consider myself foremost as a city-dweller, even though I now live in a small village in the Pennine hills, as I commute to Manchester daily and love the city passionately. A side effect of this, alongside having worked in urban economic policy for a decade, is that when visiting small towns and cities, I tend to always ask myself ‘what do people do here? How is the economy structured? How do these places survive?’.

But in both Lincoln and Newark, I see places that are well kept, with plenty of independent companies, relatively few empty shops, and a generally positive vibe to them. Economic research and development policy has, over the past decade, been focused on cities as the engines of growth, perhaps to the exclusion of other parts of the country, and this divide between rural and urban can be seen in party-political affiliation, the Brexit vote and other indicators. The aftermath of the financial crisis and the recession, and particularly the decision to leave the European Union, have reawakened interest in the places outside our cities, and we are now seeing some excellent research being published on towns, particularly by the new think-tank [Centre for Towns](http://www.centrefortowns.org/).

So, spurred on by these thoughts (which, I’m conscious, come from a lack of experience and understanding in non-urban economies), I’ll be looking more closely at some of these in the coming days and weeks, seeking to answer my questions and to better understand how – and if – they are different to cities, and to learn about their challenges and opportunities they face in their futures.

I’m particularly interested in those towns and cities that are not within easy striking distance (or economic capture) of major cities, as I think those that are, whilst having similar challenges, have very different policy requirements for their solutions. I’ll return to these questions and more, hopefully with some answers, soon.