---
title: "Taking back control?"
author: "Christian Spence"
date: "2018-09-04"
categories: [devolution, governance]
---

This post comes on the back of an [outstanding piece](https://www.politico.eu/article/notes-from-beyond-westminster/) in Politico by Jack Blanchard. There’s lots worth reading there in full, but I want to dwell on the comments raised in Wigan and highlighted by Tom Forth in [this tweet](https://x.com/thomasforth/status/1036641099924865024).

Whilst lots has been written by both academics and policy advisors (think-tanks, etc.) about devolution and the importance of what more recently has become known as functional economic areas, the debate around place and identity and their relationship to governance has mostly been left to the academic world, meaning much of the detailed research and thinking lingers in journals and academic conferences and doesn’t permeate what I might call (and hope I can get away with it in my new role in academia) the real world.

Lisa Nandy (MP for Wigan) comments about the challenges of ruling elites and their distance from the people they serve. A number of authors have raised this as a key issue in the Brexit vote, that people feel disconnected from a ruling elite in Brussels, and would prefer one closer to home. I would argue that the problem has been a distance from the ruling powers in Westminster and Whitehall rather than Brussels, but that will have to wait for a future post.

But isn’t this a problem that devolution was meant to solve? After all, the good residents of Wigan have part of a more local government since the 1970s reforms, first in Greater Manchester Council, later through the voluntary working arrangements of the Association of Greater Manchester Authorities (AGMA), and most recently as a constituent of the Greater Manchester Combined Authority. The whole point of these reforms (at least the most recent – the 1970s reforms and their 1980s reversals are worth a entire suite of posts on their own) was to bring more power closer to the people, but if the population feels disenfranchised by these, then where to we go from here?

History may help us out to some degree. The 1970s reforms took power away from smaller councils and passed it up to new districts and and an overarching metropolitan tier. In terms of direct democracy, it’s not clear that more power was given to either local areas, or to their voters to effect change. And it’s perhaps that latter point that’s where the disconnect may be the greatest.

Power given if useless if it cannot be shaped. Wigan (and other boroughs like it across the country) have markedly fewer powers today to actively shape their places in response to the wishes of the local people. The democratic feedback loops are at best tarnished, and may be broken. There is little point in championing the powers that Greater Manchester now has (and they have noticeably increased) if the people of the boroughs do not feel as if they can shape them.

Whilst this is in danger of sounding like a call for increased direct democracy, that’s not what I’m suggesting: that is an idea based in good intent but riven with challenges in its delivery (see Brexit for a recent example). But voters must be able to feel that they can influence and shape the fortunes of their place, and it’s not clear that the current model can do that.

The creation of the directly-elected mayors, whilst opposed by a majority, I think will, over the longer term, provide a useful tool in repairing the democratic deficit, but I suspect that the powers they currently hold are insufficient to enable that to happen on a scale that’s sufficient. The mayors will always be challenged by the image of ivory towers at city hall, but other places around the world have solved this with a far more extensive and sweeping powers at a local level than this country has seen in the past century or more, and arguably ever. (There’s another piece I must write on the history of sub-national governance in the UK and why it is so centralised, but that’s definitely for another day).

So, to come back to place and identity, this raises a final question for now: to where do places like Wigan see themselves as belonging? As someone who was born and brought up there, I hope I have a sliver of understanding about this. During the 1980s and 1990s when I lived there, it was clear that Wigan didn’t naturally look to Manchester as its neighbour, partner or bigger brother. Liverpool was a more natural urban parent, but Warrington and West Lancashire towns like Skelmersdale, Ormskirk, and even Preston, were mentioned more by the people I knew than Manchester ever was.

The 2001 census placed Wigan in the same Travel to Work Area (TTWA) as Manchester, and Greater Manchester, in these maps, was a near perfect fit for the mobility of its population. This changed in the 2011 data, when Wigan became paired with Warrington, and Greater Manchester gained Cheshire East and Macclesfield within its reach. Part of this is changing public transport availability, part is the phenomenally rapid growth of Warrington and Cheshire’s economies during the 2000s (again, worth a post on its own).

We shouldn’t worry about fitting governance structures exactly onto changing patterns like these, as the borders will be endlessly shifting. But identity is much less mobile, and representation within larger structures matters to individuals’ feelings of autonomy and the validity (real or perceived) of their governments.

This is where devolution can help, but we need a level of support from politicians, as policy can’t fix all the problems. In reality, Wigan is probably best served within the Greater Manchester structures, where the scale for investment, and for its returns, is greater. But in the end, the people of Wigan will need to feel they have adequate representation, and that their voice is heard equally with those of more prosperous and more vocal boroughs like Manchester.

Andy Burnham, the mayor of Greater Manchester, has made clear that he wants to see greater representation of, and policy designed to benefit, the outlying areas which have seen relatively little investment compared to the city centre and wider urban core. But the challenge is that this mustn’t come as a form of jam-spreading, where spend is dictated solely on a per capita basis (I disagree with IPPR North and its policy recommendations for transport spend for the same reason – spending should be balanced more towards need than equity).

Redistribution is important here, and will remain so for ever more, for no country is equal throughout. But in areas like Greater Manchester, where the whole does not generate net returns from which to distribute, this places a further challenge on the political messaging. Whether local spend is in Manchester or Wigan, it will ultimately be driven by money redistributed from somewhere else. But Greater Manchester as a whole is aiming to correct its fiscal balance, and balance its books over the coming decade. That will give the politicians greater leeway in taking distributive decisions.

So, for now, whilst policy can go someway to correcting the problem, it will take a long time for that to come (and fiscal devolution – the ability to raise and spend your own money – is critical to this). In the shorter term, the solution lies with politicians to create the narrative and lead the people. On a national scale, this is woefully lacking. At a local level, while it has a way to go, the signs are more positive.