---
title: "Fantasy economics from a fantasist government"
author: "Christian Spence"
date: "2022-09-23"
categories: [budget]
---

Liz Truss said she was comfortable taking unpopular decisions. For the general public, this “fiscal event” may not, yet, prove unpopular, but it may prove controversial or even courageous.

To produce a multi-billion pound stimulus package at a time of high inflation may be controversial. That it is wholly unfunded at a time of rapidly rising interest rates may be courageous.

As Sir Humphrey Appleby said, “Controversial” only means “this will lose you votes”. “Courageous” means “this will lose you the election”!

That the Chancellor’s actions have both weakened Sterling (causing higher inflation) and increased gilt yields (increasing the cost of borrowing) still further would have even Sir Humphrey grasping for euphemisms.

The Chancellor is betting the house on a suite of measures which are unlikely to deliver what is being asked of them. There is little to no evidence that the rates of tax in the UK form any substantive barrier to increasing the long term trend growth rate of the economy.

The scale of unfunded borrowing announced today is, by any measure, extremely high.

Reducing the basic rate of income tax, and abolishing the additional rate, alongside reversing the increase in national insurance contributions and cancelling the increase in corporation tax will, collectively, cost the public finances £45bn a year by 2024.

With other announced measures adding an additional £72bn to the deficit (now expected to be £234bn, over 10% of GDP) at a time when the two-year cost of government borrowing has increased from 0.4% to 3.9% over the past year will cost even more.

Adding this additional unfunded borrowing will increase those rates further still, compounding the problem.

The scale of the effective stimulus is likely to cause the Bank of England’s MPC to increase Bank rate faster than previously expected, further increasing the cost of borrowing yet more.

The forward curve on Bank rate now has a 50% probability of a 100bps rise in November with peak rates next year up from 4.75% to 5.4%. This will further compound the problems that the chancellor says he wishes to solve.

It is painfully clear why Treasury resisted an official OBR forecast with these policies.

The removal of the additional rate of income tax is, in terms of cost to the Treasury, insignificant (and may actually raise revenue – NB HMT revenue is not economic growth), though its political message may be stronger.

In removing this band, the Chancellor points to the complexity of other OECD countries’ tax systems and how administrationally burdensome they are, whilst failing to realise that they have higher levels of productivity, higher levels of investment and stronger growth.

If simplifying was important, then tackling the removal of the personal allowance above £100,000 would have been a better place to start. But simplification isn’t really on the Chancellor’s agenda, as he’s also abolished the Office for Tax Simplification.

There is much confusion in the chancellor’s statement, saying that we need to increase the number of people in work, but he is tackling part-time workers rather than the huge increase in economic inactivity of the past few years.

That will only be supported by investment into health which will enable people not working for health reasons to return to the labour market, but the money for this is no longer available after a swathe of tax cuts.

Stamp duty is a tax which the majority of economists agree is unhelpful and its reduction is a good thing in and of itself: it makes little sense to tax people moving home.

However, this tax operates in highly-constrained market with insufficient new homes being built and housing remaining an under taxed asset with little to pay in direct relation to its value, and particularly its ultimately unproductive increase.

The cut in stamp duty is likely to be capitalised into house values, meaning there will be little to no overall change in house prices.

However, the increase in values will now, for many, fall into their mortgages at a time when interest rates are rising sharply which in turn will reduce households’ disposable income over the longer term.

Corporation tax reforms fail to understand the interaction between headline rate and the base. A £1m per year capital allowance is maintained, but reducing the rate relatively disincentivises investment compared to a higher rate.

There is too much focus on the headline rate, and not enough attention to how the base and reliefs affect behaviour.

If government truly wanted to incentivise investment (and ultimately, its lack is the fundamental barrier to growth in the UK economy), then allowances would be increased both significantly and permanently, and the corporation tax rate would be increased.

This would strongly incentivise companies to invest with only retained profits taxed at a higher rate.

If this package were to increase the trend rate of growth to 2.5%, then there is an outside chance that these changes may pay for themselves. But there is no substantial body of economic evidence to suggest that they will.

Overall this package is, on balance, more likely to increase the challenges to the UK economy over the medium term, even if it results in a politically helpful short-term stimulus before the next election.

The short-termism of UK politics is writ large in this statement, but the costs are here for the long-term.