---
title: "A city well placed to prosper"
---

_This was first published in BNY Mellon's '[Manchester 2025: the next decade of development](https://www.bnymellon.com/emea/en/_locale-assets/pdf/our-thinking/bny-mellon-manchester-2025.pdf)' in 2015._

Manchester's reinvention and re-invigoration over the past decade or more has been impressive. Shrugging off its post-industrial decline, its rebirth as a modern city is clear.

Its business heart is thriving with a large cluster of financial, legal and professional services companies and Europe's second-largest digital and creative hub. Meanwhile, cutting-edge science, innovation and high-technology manufacturing activity are inextricably linked to the strong knowledge base present in Europe's largest university population.

The city’s strength extends beyond business and includes a vibrant consumer economy, including the most extensive retail centre and busiest tourist destination outside London, and its world-leading – and rapidly-expanding – arts, culture and sport provision. It is, perhaps, this wide-ranging and comprehensive offer that has been the key to Manchester’s success.

> “The next 10 years will see growth come mostly from our strongest industries now”

Looking forward, however, the city will face challenges, as any rapidly-growing urban economy does. This includes attracting investment in infrastructure to facilitate access to jobs and transport between homes, offices and factories. The benefits of this growth must be shared across Manchester’s growing population and there remains much work to be done in ensuring that all residents are able to take part in the future economy.

The proliferation of the “hour-glass” labour market will require both high- and low-level skills with fewer and fewer positions in the middle. Meanwhile, a growing population will need somewhere to live, a problem that is increasingly being shown to be unsolvable by our current housing, planning, construction and financial systems.

The next 10 years will see growth come mostly from our strongest industries now: professional services, creative and media, advanced manufacturing, energy, logistics, arts and culture and retail, with education and health both growing in importance in response to the demands for a skilled workforce and the challenges of an ageing one.

But if history teaches us anything, it is that Manchester’s strengths are its resilience and ingenuity. Economic forecasting makes clear that our ability to predict the future is poor, and that it is managing and responding to change, rather than foreseeing it, that allows us to best capitalise on the opportunities that Manchester in 2025 will give us.

We may not know what it will look like in the future, but Manchester will thrive.