---
title: "Centre for Cities needs a fair hearing"
---

_This blog was [first published](http://www.thebusinessdesk.com/northwest/news/2007991-guest-column-christian-spence-greater-manchester-chamber-centre-cities-needs-fair-hearing) in TheBusinessDesk.com (North West) on 14 August 2017._

Last week, the UK think-tank Centre for Cities released a report, [Should we move public sector jobs out of London?](http://www.centreforcities.org/publication/move-public-sector-jobs-london/), the conclusion of which was that, whilst the relocation of parts of the BBC out of London to Salford brought jobs to MediaCityUK, its wider impact on employment across Greater Manchester (GM) was limited. In terms of impact, let’s say that Centre for Cities media hits KPIs will be looking much stronger today than they were before its launch. Reaction against the report was strong across social media, with many saying that it was typical of a London-based think-tank to do the North down, or similar (and unrepeatable). It was enough to provoke even Greater Manchester Combined Authority (GMCA) to issue a press release saying it rejects the “flawed report”.

Sean Anstee, GMCA’s lead for employment and skills, and the Mayor of Salford, Paul Dennett, both stressed the positive effects seen since the BBC’s move of clustering and innovation in the creative and digital sector, and rightly highlighted the significant growth of this industry in GM over the past few years, but the chair of the GM LEP, Mike Blackburn, went further, saying “a report that says the BBC has not had a positive impact on Greater Manchester is ridiculous”.

I agree with Mike: it would be ridiculous if a report said that, but the crucial point here is that this one doesn’t. This report, a welcome addition to the literature in this area, focuses on net employment growth, an area where previous policy-driven relocations have often fallen well short of their lofty ambitions (the National Audit Office suggested in 2013 that the BBC’s move to MediaCityUK could generate 15,000 jobs, more than twice what has been achieved there so far). But just because overly-ambitious targets are not met does not mean that there hasn’t been measurable success.

The Centre for Cities report highlights the jobs growth in the creative, media and digital sectors in Greater Manchester overall and that this growth has outpaced the national average in Greater Manchester; some of this is certainly due to the “BBC effect”, but is also due to Manchester’s longer-run reputation in these sectors and its increasing attractiveness as a city in which to do business in these areas. But the crux of the report is that the net job gain, the overall employment level impact, on the local economy when organisations are moved like this, is limited, and displacement can make up a large share. This is not new: the UK’s history with policy experiments like enterprise zones also shows significant amounts of displacement into these areas from others, with net gains lower than initially expected.

But here’s the important part from a policy wonk’s point of view: none of this contradicts the previous research, or the GMCA’s reactive press release, that shows positive wider social and economic benefits than relocations like this can produce, and it’s that “can” that’s important. Success is not, like in other areas of life, guaranteed, and certainly not in all areas. The arrival of a large body, like the BBC, can provide lots of positive benefits and spill-over effects, but these are predicated as much on the wider ability of an area to capitalise on it as they are by the move itself.

Arguably the move of the BBC into Salford was highly likely to be successful overall: a huge addition of a major national body with global reputations into a city with a strong track record for innovation, creativity and maximising opportunities would likely fare well. But this doesn’t mean that all indicators will be hugely positive, nor that all cities could pull this off equally well. Within these broader remits, it’s questionable whether, overall, a weak net employment growth in the locality really matters, but it does matter if that’s the reason for doing it in the first place.

Debates have raged for decades in the UK about relocating jobs out of London to the regions. From Harold Wilson’s policies to place new government departments outside London and his Industrial Development Act through to more recent cases covered in this report (the Office for National Statistics’ move to Newport is also looked at and comes out even less well), it’s an area that’s had lots of policies but, in truth, few major successes. Often, this is because the policy aims are poorly designed, with more wishful thinking than tangible and achievable outcomes. The BBC wanted to promote better regional coverage and connect better with its regions: the move to MediaCityUK has helped it to achieve that, and Greater Manchester is making the most of this opportunity to maximise its own growth. This is all good news, but this report highlights that, if you’re expecting relocations like this to spur large-scale job creation in and of themselves, you’re unlikely to succeed. But that doesn’t mean you shouldn’t go ahead: life in policy isn’t black and white.

And it’s this subtlety, and the way that the reaction to this report has tackled it so poorly, that’s the major thing we must learn from. There is no contradiction between the Centre for Cities report and the success of the sector as a whole in Greater Manchester: they’re measuring different things. From a policy design and formulation perspective, this detail is important. When leading figures come out and shout down a report for saying something it doesn’t say, it’s disappointing, particularly when Greater Manchester has shaped itself over the past decades as a rigorous evaluator of evidence-based policy.

Centre for Cities has been working tirelessly for years on promoting the growth of the UK’s cities, the over-centralisation of the UK economy in London, and pushing forward the devolution narrative to support better, more balanced growth across the country. To say it is providing ammunition to those who want to keep power in Whitehall is dangerously oversimplifying a complex area. Yes, this report could be read that way by people whose interest it is to keep these old battles alive. For those of who want to move things forward, with challenge, evidence, and a foot on the ground, this is welcome ammunition. But we’ve got to stop firing the bullets at others who are on the same side.