---
title: "Retail in Manchester City Centre"
---
_This piece was first published in Greater Manchester Chamber of Commerce’s member magazine, 53 Degrees, in May 2014._

With Manchester city centre bucking the national trends and going from strength to strength, Christian Spence, Head of Business Intelligence, looks at some of the changes in the retail sector over the past few years and how Manchester has not only survived, but positively thrived.

## The high street’s decline is not inevitable

There has been much talk of the death of the high street and the statistics partially bear this out with retail sales stagnating for four years from late-2007. Whilst we’ve seen a strong recovery since the middle of 2013, some high streets are still showing signs of considerable distress. However, the problems go beyond macro-economics and are more to do with a changing culture. People’s expectations have changed, and not all towns have yet understood, or been able to respond to, the change in customers’ habits.

## The bad guys

Business rates, parking charges, out-of-town centres and the internet have all been blamed. Business rates have become more vilified with charges currently linked to rental value at the top of the market in 2008 despite some rents falling by over 50% since then. Some argue that this has given an advantage to companies who operate solely on-line.

Ever since London’s Brent Cross opened in 1976, there have been concerns that large centres with free parking have had a negative effect on town centres. In the 1980s, government relaxation of retail sector planning policies coupled with increased car ownership meant more people were shopping in out-of-town centres: by the early-2000s nearly half of all food purchases were from out-of-town hypermarkets.

The conflict between free parking at out-of-town sites and a policy to significantly increase town centre parking charges to mitigate traffic problems in city centres may have had an all too predictable effect, particularly as out-of-town sites are able to increase the volume of free parking to manage demand, a challenge that is harder to meet in urban centres.

The internet is a disruptive technology, changing the face of entire industries in the blink of an eye. The share of internet sales is increasing at around 10% per year; 12% of all retail sales are now online and, for some segments, that share increases to over 60%. Even areas such as clothes and food are now seeing strong growth. Some businesses have balanced the “bricks and clicks” and see them as complementary to their high street presence showing that success in the internet age is possible, providing you get the business model right.

## Agglomeration’s (mostly) what you need

Back in 2007, the British Council of Shopping Centres noted “… smaller town centres have not only been affected by out-of-town development but have also suffered the impact of the concentration of development within larger town centres.” This is crucially important. The recession exacerbated an existing problem, but it is the consumer that is driving the change in the retail world.

Shopping has become less of a refuel and restock process and has evolved into a complex mix where the boundaries of retail, tourism and leisure merge. The public seeks a wider experience and the places that benefit the most are those that provide it, merging shopping, eating and drinking, entertainment and wider visitor attractions into a single user journey.

There are exceptions: some smaller village centres are thriving. Places which offer a smaller-scale, bespoke service, focused on locality, individuality and often a non-corporate nature can do particularly well, and Greater Manchester has a number of these successful, smaller centres. Essentially, high street retail has been subject to the same forces as other businesses over the past decade: success can be found in high-volume, relatively low-margin and low cost stores and in lower-volume, higher-margin specialists who have a personal offer, but those in between are being ruthlessly squeezed.

Some music stores in the UK were driven out both by iTunes and by smaller, specialist music and record stores; Tesco is feeling the pressure from Aldi and Lidl at the bottom, and Waitrose at the top. Appealing to everyone is hard for a single institution, but it’s possible in for a large agglomerative city centre to offer all the alternatives to suit everyone’s taste.

Manchester is undoubtedly one of those larger centres that has thrived and is well placed to take advantage of the recovery. To help embed that success, and build further upon it, it formed a new group to help it through.

## The Manchester Visitor Economy

The wider tourism sector generates around £6 billion to the city region and the retail spend within the city centre alone amounts to £1.2 billion. Add the Intu Trafford Centre into that and our two key shopping areas account for around one pound in every three spent in retail across the whole of the North West. Manchester is the best performing city centre in the UK outside London with its regular commuters, workers and residents accounting for 40% of all spending. The changing demographics of the city with increasing numbers of people, particularly students and young professionals now living in the city centre means there is a larger captive audience who could be successfully engaged with the leisure provision, and it is partially this population that Manchester wanted to target more effectively in a new scheme.

## Heart of Manchester BID

After consulting over 300 city centre retailers, in November 2012 a successful vote brought into being a five-year initiative: the Heart of Manchester Business Improvement District (BID). At the end of the BID’s first year, it is good to take stock of why it was set-up and what it hoped to achieve, reflecting on its first year and the challenges that lie ahead.

The BID’s primary objectives are to launch major new events in the city centre to attract footfall, develop a city centre hosts scheme to help and support visitors, cultivate a stream of activity to boost midweek and evening trade and to deliver significant promotional campaigns and partnerships to attract more affluent shoppers. These were designed to increase the overall attractiveness of the city centre to shoppers – both existing users and new visitors – repeat visits and provide a direct and tangible return on investment.

Increasing opening hours of the city centre stores and bringing new events into the city centre was seen as particularly crucial. When Manchester introduced late-night opening on Thursdays in 2005, it was clear there was demand, particularly from those who work and spend the day in the city, to stay into the evening for shopping and other activities. On other evenings, however, the city virtually closed at five o’clock. Simon Binns, manager of the Heart of Manchester BID, says: “the extended opening times of many of the city centre retailers through until eight o’clock has transformed the feel of the city in the evenings. Manchester now has a vibrant after-work culture in shops and bars every night of the week: it’s not just confined to say, a Thursday or Friday night. Today, the core retail areas are seeing significantly higher footfall and the city feels a much more vibrant area after work. Before this important commitment from retailers, Manchester suffered by seeing many of its 140,000 city centre employees head home straight after work, taking their discretionary spend with them. But now we’re seeing them not only stay in the evenings but return at the weekends with a significant increase in people coming into the city on Sundays, causing some retailers to look at staying open longer until 6pm. Capturing these additional visits gives Manchester a very different flavour: more cosmopolitan, more vibrant, a place to not just work or shop, but also linger and enjoy.”

But it takes more than just extended opening hours for shopping to convince people that staying after work is worth it. Manchester has its fair share of events, from the world-leading Manchester International and Jazz Festivals, the immensely successful Christmas Markets, as well as numerous smaller events, often located around the Town Hall on Albert Square, an area not synonymous with the city centre retail sector.

The near one million pounds raised each year through the participating members of the BID has gone a long way to delivering additional attractions. The first major event the BID helped to deliver was Dig the City, a new urban gardening festival pioneered by the Cathedral, in August 2013. With support from the National Trust, the City Council, Groundwork and the Co-operative Group’s NOMA, the traditionally quieter time in the retail calendar over summer counted over an additional one million visitors. The event increased footfall by over a quarter in New Cathedral Street and King Street and the city centre as a whole by more than 5% with half of all visitors doing additional shopping whilst there. Its success was deemed so strong that plans are already well advanced for a repeat of this nine-day event this year.

October saw Manchester turned into a catwalk with Vogue Fashion’s Night Out coming to the city for the first time. Over 160 of the city centre’s retailers took part with thousands of visitors flocking not only to the direct events but also to extra late-night opening in the participating stores, doubling the footfall normally seen. What’s particularly important about events like this is that visitors are not constrained purely to the event venues themselves, but engage with the wider city centre proposition. During the Vogue fashion events, Manchester Arndale saw a 22% increase in footfall with 120,000 people using the centre on the main night.

Manchester Arndale understands the wider benefit that these big-piece city centre events have on its and its occupants’ fortunes. It is working closely with the BID team to ensure that it, too, is closely involved in the wider strategy. Featured in this month’s Behind the Scenes on pages 12-14, Manchester Arndale has done well through the recession and visitor numbers keep increasing with 2013 recording the second year in a row with over 41 million.

The centre is currently planning its annual October student event for the 11th year, focused around the new intake of students at the city’s universities. David Allinson, Centre Director at Manchester Arndale, takes up the story. “We’re home to Europe’s largest student population of around 100,000 and they can be seen as key to the success of the city centre, with one in five of our visitors being students. Changing demographics, such as many more international students with a higher spend profile and a desire to get to know everything that Manchester offers from a global viewpoint, means they are becoming ever more important to the city’s fortunes.

“Our recent student spring event was hugely successful with live music, DJs and exclusive retailer offers. Alongside the October event we’re developing new ways of engaging the student population, particularly when students bring their wider families to the city to visit, such as through offers and social media. This is particularly important for international visitors as their spend profile is significantly higher.”

Alongside this targeted engagement from retailers, the BID team is developing a user-friendly guide to the city and its shops, bars, theatres and museums, to make international family visits as easy and smooth as possible.  

David added, “Working integrally with the Heart of Manchester BID team is key to us and I think that the successes of the BID in its inaugural year demonstrates how bringing Manchester’s retailers together serves the city centre very well. We have worked closely with the BID to deliver hugely successful and profitable Vogue Fashion’s Night Out activity, as well as seasonal celebrations such as Chinese New Year and St Patrick’s Day and we have been thrilled by the results in terms of footfall and visitor engagement.”

The benefits don’t just flow to the bigger stores: small businesses benefit too. Manchester is home to a thriving independent retail sector (18% of all city centre businesses) – the largest share outside London. They benefit from the much higher footfall figures so the winnings are not just for the larger, paying members of the BID.

This was highlighted in the larger Chinese New Year celebrations of February 2014. With the city covered in 3,000 Chinese lanterns and special food markets across the city, the event was a showcase for Manchester’s long-established Chinese community. With visitor numbers up 20% on the previous year, city centre retailers saw an increase in sales of up to 125% on the main day of the festival with footfall up 59%.

The BID’s first year has shown what can be achieved when key partners come together to invest in the city and deliver a comprehensive offer to residents, workers and tourists alike. Retail sales and footfall have increased faster than the national average and total visitors to the city have increased by 14%. The Heart of Manchester BID has many additional events planned for its second year and beyond: for more information visit [](www.cityco.com/heartofmanchester).