---
title: "Take the bus"
---

_This piece was first published in Prospect Magazine in ._

It’s the most popular mode of public transport—and the most ignored

On 4th July, when Americans were celebrating the anniversary of their independence, the parliament that centuries before had failed to represent them was questioning its prime minister. The leader of the opposition concentrated his questions on a topic missing from the PM’s folder—Britain’s bus services. Jeremy Corbyn was lampooned for choosing this obscure subject.

Theresa May’s reply, that buses are an issue for local authorities, was wrong. While she pointed to the new powers in the Bus Services Act 2017, she failed to mention her predecessor’s Transport Act of 1985. This privatised and deregulated bus services outside London, reducing local authorities’ role to the point where all they did was write the cheque.

The prime minster at the time, Margaret Thatcher, suggested that those older than 26 who used buses were a failure, but, with 4.9bn bus journeys in the UK in 2016/17 compared to 1.7bn by rail, why don’t politicians take buses more seriously? Perhaps the problem is that those who set transport policy don’t use them. Our views of the world are shaped intrinsically by our own experiences. That means that transport policy tends to be set to the benefit of those who design it. And that means the experience of London-based civil servants and politicians. And that means trains.

The recent timetable change chaos, while inconveniencing millions, focuses only on the experience of a small share of the population. Nearly two-thirds of train journeys start or end in London, and one-third of all commutes to central London are by rail. This is not the normal experience for the rest of Britain. In Greater Manchester, cars dominate and account for 70 per cent of commutes. Even though Europe’s busiest bus corridor runs past my university campus, only 10 per cent of all journeys are by bus, and only 4 per cent by train (6 per cent if you include the Metrolink trams).

London’s buses have been successful: they are regulated, have a flat fare structure, provide contactless and integrated ticketing, receive a healthy subsidy and consequently account for around half of the UK’s annual bus journeys. Even outside London, buses are more important than rail: in Greater Manchester, 80 per cent of public transport journeys are by bus, but rail gets the attention and the subsidy.

Buses have an image problem. Outside London, the user base is overwhelmingly working class and, by definition, poor. The National Travel Survey shows that, in London, the richest fifth uses buses as much as the poorest, but in the rest of the country, the top 20 per cent make only half as many journeys as the average and two-thirds less than the poorest 40 per cent. Rail, however, is used twice as much by the wealthiest fifth than the average, and three times more than those from the bottom half of the distribution.

The focus on rail travel with large subsidies and the capping of season ticket costs disproportionately supports the wealthiest. Current policy gives the richest 10 per cent of households nearly twice as much transport subsidy as the poorest. Transport investments are too often focused on improving city-to-city journey times, frequencies and capacities, but this risks focusing too heavily on the needs of a small and socially distinct group of people who can afford to commute long distances into relatively well-paid city centre employment.

Buses are a vital part of public transport, and form a critical part of social infrastructure for the poorest who often don’t own cars and rely on taxis. They could, as we see in the capital, provide a better solution for many of our growing cities. National government does not see the importance, but local governments do. England’s new mayors are now seeking to maximise the opportunities of bus regulation in their areas, but this will take time—and money, which is in short supply. But there needs to be control, and that control needs to be local.

The devolution revolution, heralded under George Osborne, has slowed, but increasingly this is where we must look for solutions. As in so many other areas of policy, the Westminster model continues to fail most of the country, and those powers should be given to those who can use them best.