---
title: "Taxing online sales is not the solution"
---

_This blog was [first published](https://www.manchestereveningnews.co.uk/business/business-news/chamber-blog-christian-spence-head-5380955) in the Manchester Evening News on 29 July 2013._

It was reported in last week’s Manchester Evening News and in the national press that Justin King, chief executive at J Sainsbury, and his counterpart Dalton Philips at Wm Morrison have asked government to consider levying a tax on online sales.

They complain that there isn’t a level playing field between their bricks-and-mortar companies and those who trade mostly in the digital sphere. Chief executives of online firms such as Ocado and Greater Manchester’s own N Brown amongst others responded, rightly noting that this rather misses the point: the problem is not that online is under-taxed.

Rather, it is that traditional high street stores are overtaxed.

At the Chamber of Commerce we have been vocal for years about the horrendous burden of business rates on all sectors of the economy, but particularly on retail.

Having increased by 13 per cent over the past three years and linked to a property valuation at the height of the market in 2008, many businesses are now paying more in business rates than they are in rent.

This is a ludicrous position and, to make matters worse, the expected revaluation this year has been kicked two years down the road meaning those top-of-the-boom prices are locked into this tax for another 24 months.

An online retail sales tax also ignores the reality that many small- and medium-sized businesses, and particularly start-ups, are operating increasingly in the digital world. Depending on where any legislation drew the boundaries, you could see self-employed people and their eBay stores falling within the scope of this tax. It also fails to acknowledge that these large supermarkets are themselves seeing an ever-increasing share of their sales take place over the internet.

The future of online retail is strong and only likely to continue growing as a younger, apartment-dwelling, digitally-enabled population gets ever-more used to buying groceries via the web.

Finally, the whole argument flies in the face of why more purchasing is taking place on line: it is more convenient, less expensive and places the buyer in charge of the when and where.

This shouldn’t need spelling out, but sadly it does: This Is A Good Thing. Civilisation as a whole moves forward by making steady improvements in efficiency, productivity and value. This means that we, the consumer, get to “live well for less” and “get more of what matters”. You’d think that the supermarkets more than anyone else would understand that.