---
title: "The seven deadly sins of business rates"
---

_This blog was first published in an abridged format by British Chambers of Commerce in March 2017._

Whilst nobody likes a tax, business rates is one that people love to hate. As a Fellow of British Chambers of Commerce (BCC) leading on the reform of business rates for two-and-a-half years, I’ve heard more nightmare stories from members than for any other issue, and have spent hours in rooms in Whitehall working through proposals with other business groups, local authorities, HM Treasury, the Department for Communities and Local Government (DCLG) and the Valuations Office Agency (VOA). I often say, and only partially in jest, that I started a 12-month project over two years ago and think I may now be approaching the half-way point.

The history of business rates is a long one. Many know about the large changes to business rates that took place in 1990 under the Thatcher local government reforms when the level of rates was nationalised, but not many know that the system dates back a lot further: the Act for the Relief of the Poor 1601, passed under Elizabeth I, is the first piece of legislation.

There’s two other things from deep history I’d also like to reference here. Firstly, from the 17th-century, the words of Jean-Baptiste Colbert, minister of finance for King Louis XIV of France, and secondly, from the 18th-century, the wisdom of Scotland’s own father of economics, Adam Smith. Colbert said that “the art of taxation consists in so plucking the goose as to obtain the largest amount of feathers with the least possible amount of hissing”, and Smith laid out what he considered were fundamental principles of economic taxation: equity, certainty, convenience and economy. It is highly questionable whether the UK’s business rates system meets any of the above.

## How did the issue start?

As an issue, business rates really came to the fore after the recession. Commercial property prices tumbled as businesses struggled or failed, plenty a strong downward movement on rents. Companies were often able to renegotiate leases as supply increased and demand softened. But business rates were not only locked at their pre-recession level, remaining as a fixed percentage of the assumed market value of the property at the previous revaluation in 2003, but increased further in 2010 when business rates became a higher percentage of higher values, calculated against rents two years previously in April 2008, about as close to the top of the overheated market as it was possible to be. Wanting to minimise large changes to the rates payable, the scheduled revaluation for 2015 was delayed, giving the system another two years to become even more out of sync with the real world.

In April, the changes in the UK commercial property market since 2008 will be passed into the business tax system in one go (albeit with some limited transitional arrangements). The result of that has been clear in the press over the past few weeks, as the house of commons passed its Brexit bill and then ran off for half-term, allowing a media frenzy on rates to emerge with little comment from government ministers, showing that Colbert’s principle is being violated: the goose is hissing – loudly.

## Calling for reform
Working with its members, BCC developed seven key principles of the current system which require fundamental reform.

### 1. Above the line

Business rates is an input tax that it is payable regardless of turnover, profit, or ability to pay. Government policy is driving up input costs to businesses, whether through environmental taxes, increased minimum wages, auto-enrolment for pensions, higher employer national insurance or the forthcoming apprenticeship levy. At the same time, output taxes, particularly corporation tax, have been falling steeply, so revenue raised from business increasingly comes from the input side, burdening business regardless of its success. This violates Smith’s equity principle, that tax should be “… in proportion to their respective abilities, that is, in proportion to their revenue …”.

### 2. Predictability of income

Business rates is neither pro-cyclical or counter-cyclical. Instead, it’s how-much-would-you-like-to-raise-next-year-Mr-Chancellor-cyclical. The uprating of the national multiplier each year, currently at RPI but expected to change to CPI in 2020, means that government revenue from this tax on rental values increases every year, even if rental values fall. It has an in-built escalator, something that when applied to fuel infuriates everyone, but slips by here with little issue. It’s just about the only tax in HM Treasury’s army that does this and it’s hard to see why it should continue. Of course, it’s convenient for government, but meaningless for business. See the canon of certainty above for Smith’s view. Ours is that indexing should ideally be abolished entirely, allowing the system to flex with the market.

### 3. Economically unresponsive

The slow frequency of revaluations (normally every five years, but currently seven) means rents and rates become disconnected over time. This can work in companies’ favour, and arguably that has happened in place like London since 2008, where rents have risen much faster than rates, but overall it means that areas with weaker property markets subsidies those with faster economic growth. In this sense, this partially violates Smith’s canon of certainty, where tax payable “… should be certain and not arbitrary”. A system which levies a percentage of what your property’s value was, or was thought to be at a previous time, is not ideal. The debates around Council Tax valuations go to the heart of this exact problem as well. Our view? Speed up the revaluations to keep up with the market, but you’ll have to change the system, because …

### 4. Administrationally complex

It’s hard to get across just how bureaucratic this system is. If you operate a large site with a variety of uses, e.g. office space, toilets, kitchens, reception, warehouse, yard, factory, and have major plant and machinery including such modern-fripperies as air conditioning and micro generation, your valuation formula may not just run to dozens of line, but dozens of pages. An extra x% for one thing, subtract y% for another. It’s insane, and costs a fortune. It also generates a lot of appeals – the 2010 revaluation resulted in over a million appeals. When a system generates tax bills that nearly one-in-two payers feel the need to dispute, there’s something wrong. There are now so many appeals, that the back-log is nearly 300,000.

Each of those businesses is required to pay these rates, every year, until the appeal is resolved or rejected, meaning many will pay more than they should up to seven years after the valuation was first arrived at. Smith’s third canon of convenience, that tax “…should be levied in such a manner … that it affords the maximum convenience to the tax payer”. It’s hard to see how this is convenient. Also, the costs of centrally valuing every property (and more besides), only to give 100% relief to around to one-third of them isn’t efficient. That’s why we’ve argued for a self-exemption for the bottom-third of properties. Just submit your lease details, show that it’s below the level, and nobody needs to visit you and measure how big your toilet space is. That helps us get in line with Smith’s canon of economy, too: the cost of collection should be a minimum.

### 5. Perverse incentives

The administrational complexity caused by including productive investments in the valuation creates perverse incentives. Why improve your premises if you’re going to be taxed on the increase in value? Why invest in machinery if it will add to your tax bill at the next revaluation? And it also creates odd incentives on the recycling of government money. Want to follow government advice and decarbonise your energy supply to try and reclaim some of those environmental input taxes I mentioned earlier? Go ahead, and government will subsidise your investment through schemes available from the Department for Business, Energy and Industrial Strategy (BEIS), but DCLG will come along later and tax you for doing so. So we have a system where BEIS levies taxes on your energy and then gives you subsidies to change your behaviour, but if you do, VOA will come and visit you to work out its value and ask DCLG to tax you on it. This does not meet any criteria of tax efficiency. See Smith’s canon number three.

### 6. Disconnect between business and local government

One of the most common complaints about business rates is that companies simply don’t know what it’s there for or who receives it. “I don’t even get my bins emptied!” is a common response. Your local authority bills you, historically sending it all (now just half) to Whitehall who keep some then send it back to local authorities under a complex formula linked to deprivation and need. The system lacks significant transparency and the tax causes resentment between business and local government. The move to 100% retention by 2020 (though some areas will start a pilot this April) will set out a framework where this relationship could be improved, but it won’t happen on its own. For that to occur, there will need to be significant engagement between local authorities and their rate payers, and things like infrastructure levies may help, but there is a lot of work to do. It’s also questionable how much additional revenue full retention will allow for local government, but that shouldn’t stop this: the bigger principle here is restoring local accountability and both empowering spending decisions to be taken locally, and encouraging it to be done so openly.

### 7. Large by comparison

This has been the big sticking point in reform. Government, as part of its ongoing fiscal consolidation, has insisted that any changes to business rates must be revenue neutral, i.e. however much it raises before the reforms, it must raise afterwards (plus indexation, of course). This means that the winners and losers are amplified, as the rules make this a zero-sum game. As government has been happy to cut revenue by lowering corporation tax, clearly this is not just a cash issue. The challenge, of course, is that business rates is so entwined in the local government finance system that large changes to revenue and the system overall would require large-scale reform of local government and local government finance. Eric Pickles, when Secretary of State for DCLG, said there was a pearl-handled revolver in his drawer for anyone who suggested such a thing. That gives you a pretty good idea of how interested government would be in genuinely tackling this properly, from the ground up.

But there’s another dimension to this which I suspect is where the blocks on radical reform come. Basically, it raises too much money. At £26bn, the UK raises a larger share of taxation from property taxes than any other developed economy, and around double the OECD average. That, combined with its complex twinning with local government, means even small changes can have a disproportionate effect on the spending power of town halls. Corporation tax can be changed easily as it goes to central government and mostly funds central spending so large changes can be absorbed. I fear that not only does the fiscal neutrality argument stop serious reform, it actually makes the matter worse. The larger the revenue share gets, the harder reform in the future becomes.

## Efficient tax theory
Those are the key areas showing why we want reform, but there’s one last thing I want to touch on. There have been a number of economists over the past few weeks – mostly those I take seriously as good quality academics and practitioners of efficient tax theory and good quality public policy and who I often agree with – who have put forward the argument that business rates, as a tax on property value, is broadly efficient and has a number of good comparisons with a land value tax (LVT), something which many economists would ultimately prefer. Their argument often includes comments that increasing something’s value should increase the nominal amount of tax payable, and that, in its similarities to an LVT, broadly encourages economically efficient use of a finite resource like land.

I feel that there are some elements of truth in this, but also that it mostly obfuscates, or entirely misses, the areas where the similarities to a LVT are weakest. Firstly, business rates is a tax on property value, not land value. That means the relationship is close, but not very, and varies hugely depending on the use of the property itself. The vagaries of valuing large sites on the central list such as power stations show how highly approximate this process can be. Secondly, plant and machinery is included in the valuation, which would have impacts on the property value but not the land value. This is the area where I feel the difference between business rates and an LVT is the largest and, in arguing for the removal of plant and machinery, we specifically included a comment that in doing so, you would allow the business rates system to operate in a way more closely related to an LVT. Finally, there are two ways of looking at a tax – deadweight costs of the system itself, and the level at which it operates.

I’ve outlined above the problems with the first of these, that the system simply isn’t efficient, but the rate at which it is levied matters too. A key piece of economic tax theory – the Laffer curve – speaks directly to this in that there are optimum rates of taxation for both revenue raising and economic distortion. Here is where business rates, compared to either an LVT or to Council Tax – another example of a property value tax – sit as an outlier. No-one would countenance Council Tax or an LVT being set at the rate business rates currently are. The rate for 2017/18 is likely to be over 50%, meaning the tax take on property value is inordinately large. Combine this with the all too clear failings of the UK’s planning system to provide adequate land in the right areas with the right permissions, and you’re effectively levying one of the highest rates of tax in the UK economy on one of the most poorly designed systems with little ability to react to market conditions.

Put all this together, and it’s no wonder that Colbert’s goose is hissing.